apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: estbndlt/tickets
          # image: us.gcr.io/ticketing-dev-409907/tickets
          env:
            - name: JWT_KEY
              # command: `kubectl create secret generic jwt-secret --from-literal=JWT_KEY=SECRET`
              # command: `kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf`
              # where SECRET is a value you choose
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          # steps to run
          # - update code
          # - build the docker image with latest tag in service directory
          #   (default if not specified with estbndlt/tickets:latest)
          #   - command: `docker build -t estbndlt/tickets .`
          # - push image to docker hub in service directory
          #   - command: `docker push estbndlt/tickets`
          # - create the pod in k8s directory
          #   - command: `kubectl apply -f tickets-depl.yaml`
          # - run the command to rollout deployment in k8s directory
          #   - command: `kubectl rollout restart deployment tickets-depl`
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  type: ClusterIP
  # `type: ClusterIP` is the default and is not needed
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
